### ISSUE TITLE
.NET Alpha SDK

### ISSUE THREAD

**Issue by toddbaert** [open-feature/dotnet-sdk#1]
Alpha Checklist:

- [x]  spec compliant
- [x]  contains test suite which verifies behavior consistent with spec
- [x]  contains test suite with reasonable coverage
- [x]  automated publishing
- [x]  comprehensive readme

**Comment by benjiro** [comment]
@beeme1mr i think we can close this one out after https://github.com/open-feature/dotnet-sdk/pull/41 has been merged

**Comment by beeme1mr** [comment]
Yep, I agree.
