### ISSUE TITLE
[FEATURE] implement standard error classes

### ISSUE THREAD

**Issue by toddbaert** [open-feature/dotnet-sdk#110]
### Requirements

We already have [error codes](https://github.com/open-feature/dotnet-sdk/blob/main/src/OpenFeature/Constant/ErrorType.cs) defined, but it would be nice to define error classes to make things a bit more ergonomic for contributors. Basically something like is already implemented in [this contrib](https://github.com/open-feature/dotnet-sdk-contrib/tree/main/src/OpenFeature.Contrib.Providers.GOFeatureFlag/exception) ; simple classes wrapping these error types that can easily be thrown.

**Comment by valentk777** [comment]
Hello, I would create classes for each type (+ base class). If this is expected, I can create PR with changes. :)

**Comment by toddbaert** [comment]
@valentk777 , yep, that's what I had in mind. The link above to a contrib/provider which implements it's own is a good outline (they could be deleted from that provider and the provider could use the errors you add to the SDK).

I will assign you the issue.

**Comment by valentk777** [comment]
PR is ready for review. Sorry for this chain of closed PR's. It was naming issues and signature issues. I fixed all of them and now PR ready for reviews :)
