### ISSUE TITLE
System.Collections.Immutable needs to be updated to allow for version 7

### ISSUE THREAD

**Issue by danielp37** [open-feature/dotnet-sdk#136]
Is there a reason why the PackageReference to System.Collection.Immutable doesn't allow version 7. Version 7 has been out for 8 months now and this restriction is preventing us from being able to use this library.

**Comment by toddbaert** [comment]
Hey @danielp37 ! Thanks for opening this issue.

I've removed the upper bound on this dependency [here](https://github.com/open-feature/dotnet-sdk/pull/137).

cc @benjiro @kinyoklion do you think there's a reason to put one on this package?

**Comment by toddbaert** [comment]
After some discussion we've decided just to increment this upper bound. A bit of a bummer, since we might be back here in a year unless we automate this somehow. Removing the entire upper bound seems risky as @kinyoklion notes in the PR.
