### ISSUE TITLE
[DOC] Update readme to follow new template

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/dotnet-sdk#145]
### Change in the documentation

Update the readme to follow the [new template](https://github.com/open-feature/.github/tree/main/templates/READMEs). Once this is ready, the documentation can be configured to pull from the repo automatically.

Examples from other repos:

- https://github.com/open-feature/java-sdk
- https://github.com/open-feature/js-sdk/tree/main/packages/client

**Comment by DaryaYuk** [comment]
Hi there! I am a junior technical writer and I want to help you. I'm excited to be assigned to work on it
