### ISSUE TITLE
Generate SBOMs for .NET components

### ISSUE THREAD

**Issue by toddbaert** [open-feature/dotnet-sdk#159]
We have SBOMs currently for Java and Go. We could use them here as well. I recommend this utility: https://github.com/marketplace/actions/cyclonedx-net-generate-sbom (we're using the clyclonedx format elsewhere and it's popular).

Definition of done:

- SBOMs generated and attached to release artifact in GH, or otherwise made publicly available (for every release)
- only includes dependencies of module in question (not of repo)

**Comment by jenshenneberg** [comment]
@toddbaert : Do you mind me picking this one up?

**Comment by beeme1mr** [comment]
@jenshenneberg that would be great, thanks!
