### ISSUE TITLE
[FEATURE] add in-memory provider to SDK

### ISSUE THREAD

**Issue by toddbaert** [open-feature/dotnet-sdk#165]
Add `InMemoryProvider` to SDK. See [spec](https://openfeature.dev/specification/appendix-a#in-memory-provider).

Tasks:

- add provider
- add tests
- replace e2e tests [here](https://github.com/open-feature/dotnet-sdk/tree/main/test/OpenFeature.E2ETests) with `InMemoryProvider`.

see [Java equivalent](https://github.com/open-feature/java-sdk/blob/main/src/main/java/dev/openfeature/sdk/providers/memory/InMemoryProvider.java).

Parent issue: https://github.com/open-feature/dotnet-sdk/issues/126

**Comment by CommCody** [comment]
fwiw @toddbaert I'm looking at this, limited bandwidth, but interested in completing this

**Comment by toddbaert** [comment]
Hey @CommCody ! I've assigned you.

It's no problem if this takes some time. I'll keep it assigned to you for now.

**Comment by NeerajGartia21** [comment]
@CommCody are you working on this?
This issue looks interesting and I will be happy to collaborate with you.

**Comment by CommCody** [comment]
Mildly, I do have some work on my fork. My time is limited however, so I'm not very actively working on it.

**Comment by NeerajGartia21** [comment]
Can I continue from where you left?

**Comment by toddbaert** [comment]
> Can I continue from where you left?

@NeerajGartia21 if @CommCody has a partial implementation, maybe you'd be better off working on the Java reconnect tests, or on the Error enhancements in JS you recently commented on.

**Comment by NeerajGartia21** [comment]
Cool, that sounds good.

**Comment by CommCody** [comment]
Hi @toddbaert I was updating my code to further implement this issue, but now I can't build the main branch anymore. the build fails with:
> E:\openfeature-dotnet-sdk\test\OpenFeature.Tests\OpenFeature.Tests.csproj : error NU1009: The packages Microsoft.NETFramework.ReferenceAssemblies are implicitly referenced. You do not typically need to refer
ence them from your project or in your central package versions management file. For more information, see https://aka.ms/sdkimplicitrefs
> E:\openfeature-dotnet-sdk\src\OpenFeature\OpenFeature.csproj : error NU1009: The packages Microsoft.NETFramework.ReferenceAssemblies are implicitly referenced. You do not typically need to reference them fro 
m your project or in your central package versions management file. For more information, see https://aka.ms/sdkimplicitrefs [E:\openfeature-dotnet-sdk\test\OpenFeature.Tests\OpenFeature.Tests.csproj]  

If I disable the following line in `Directory.Packages.props` my issues are gone:
```
    <PackageVersion Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />

```

I have the following sdk installed: `8.0.101`

**Comment by austindrenski** [comment]
Thanks @CommCody, there was a similar report over the weekend, so looking into this.

**Comment by CommCody** [comment]
Fwiw I'm running these commands on windows 11. Directly against the dotnet cli.

**Comment by toddbaert** [comment]
@CommCody Hey! Unfortunately this has become a bit of a blocker.

If you aren't able to finish this in the next few days, would you mind if I take it over? I'm glad to pick up where you left off if you give me a branch, and will maintain as much of your work as possible, and make you a commit co-author.
