### ISSUE TITLE
Benchmark Suite

### ISSUE THREAD

**Issue by benjiro** [open-feature/dotnet-sdk#22]
Use https://benchmarkdotnet.org/ to make a suite of performance benchmarks to ensure OpenFeature.SDK has little overhead as possible.

**Comment by valentk777** [comment]
Hello, I want to help with this task/improvement. Do you know if this is still relevant? If yes, can someone clarify the requirements or should I create PR, and then we will discuss if you see what you like? :)

**Comment by valentk777** [comment]
Because we have only single functions to benchmark, my suggestion would be to write benchmarks for functions and add frameworks to the comparison. this would be interesting to see how differently these functions performed in multiple supported frameworks. but I want to know what would be the key point of interest from your side

**Comment by beeme1mr** [comment]
Hey @benjiro, could you please elaborate on what you had in mind?

**Comment by benjiro** [comment]
@valentk777, thanks for volunteering to do this. There are no actual requirements as such, but the following essential things are what we are looking for.

- We need to make sure the hot path is fast. Allocations should be minimal and avoided if possible.
- We need to perform a baseline benchmark to observe if future changes affect performance in a good or bad way.

As you stated, the best place to start would be to write micro-benchmarks for each method which will help isolate and measure performance. I'm happy for you to take the lead here.

**Comment by valentk777** [comment]
Initial PR has been created. Thanks for your reviews and comments in advance :)
