### ISSUE TITLE
Add Synk security scans

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/dotnet-sdk#24]

**Comment by beeme1mr** [comment]
The scans are now running but the badge isn't working.

[![Known Vulnerabilities](https://snyk.io/test/github/open-feature/dotnet-sdk/badge.svg)](https://snyk.io/test/github/open-feature/dotnet-sdk)

I'll check again later to see if it's a caching issue.

**Comment by benjiro** [comment]
I think the project in synk is only visible to people in the open feature org

**Comment by beeme1mr** [comment]
I'll look at this again once we're added to the CNCF Synk org.

**Comment by beeme1mr** [comment]
I have a ticket open with the CNCF to get on their Synk org. I'll comment on the ticket since it has been open for a few weeks already without any activity.

**Comment by benjiro** [comment]
@beeme1mr this looks to be working now?

**Comment by beeme1mr** [comment]
Yeah, it looks like the scans are running and no vulnerabilities are detected.

- https://app.snyk.io/org/open-feature/project/31f2f460-4556-414b-a45f-54970a22f1fb
- https://app.snyk.io/org/open-feature/project/e3134b34-92f2-4677-a2ea-948744d7f219
- https://app.snyk.io/org/open-feature/project/82d315ff-dad6-4da5-89f3-b166df3ad838

I'm just not sure how to create a working badge but I suppose that isn't very important.

**Comment by beeme1mr** [comment]
I'm going to close the issue since scans seem to be working.
