### ISSUE TITLE
FlagEvaluationOptions.HookHints should be optional

### ISSUE THREAD

**Issue by toddbaert** [open-feature/dotnet-sdk#28]
I think we can default this to empty in the FlagEvaluationOptions constructor.

https://github.com/open-feature/spec/blob/1bbbb361952adfa4a94618ffe66e943719be9e50/specification/hooks.md#requirement-451

**Comment by benjiro** [comment]
Good catch ill fix this one up

**Comment by beeme1mr** [comment]
Hey @benjiro, can I assign this issue to you?

**Comment by benjiro** [comment]
@beeme1mr I've opened #29 to address this.
