### ISSUE TITLE
[FEATURE] Support Returning Error Resolutions from Providers

### ISSUE THREAD

**Issue by toddbaert** [open-feature/dotnet-sdk#307]
### Requirements

As of right now, the OpenFeature .NET SDK doesn't properly handle returning error resolutions; when a provider returns an erroneous evaluation by setting the errotType, the `error hooks` do not run, and for many purposes, the evaluation appears to have succeeded.

In other SDKs, we've made changes to check the resolution details and if the errorType is set (or anything but `ErrorType.None` in the case of this SDK) we then behave similarly to if something was thrown. [We don't currently do this in the .NET SDK](https://github.com/open-feature/dotnet-sdk/blob/c471c062cf70d78b67f597f468c62dbfbf0674d2/src/OpenFeature/OpenFeatureClient.cs#L268-L281). This isn't ideal, since exceptions are generally bad for control flow and are expensive.

To resolve this:

- after evaluation, check if the `errorType` is not `ErrorType.None`, and if not, behave as if the provider threw an Exception by:
  - running the error hooks
  - setting the error message (the description of the `ErrorType` would be fine)
  - NOT running the after hooks
- add associated tests

**Comment by chrfwow** [comment]
I would like to this issue over. Could you please assign me @toddbaert ?
