### ISSUE TITLE
[FEATURE] Update merge order as per spec 4.3.4

### ISSUE THREAD

**Issue by toddbaert** [open-feature/dotnet-sdk#42]
### Requirements

See convo here: https://github.com/open-feature/dotnet-sdk/pull/38#discussion_r941479156

**Comment by benjiro** [comment]
@toddbaert can this one be closed out now since your PR resolved the missing test requirements? https://github.com/open-feature/dotnet-sdk/pull/43

**Comment by toddbaert** [comment]
yep! Closed with #43
