### ISSUE TITLE
Apply for MyGet OpenSource Account

### ISSUE THREAD

**Issue by benjiro** [open-feature/dotnet-sdk#50]
Investigate applying for myget opensource account this will be used to publish development builds

https://www.myget.org/opensource

**Comment by beeme1mr** [comment]
Hey @benjiro, do you think the [GitHub registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry) would work for development builds? I'll apply for MyGet but having to reapply annually is a bit of a bummer.

**Comment by benjiro** [comment]
I'll investigate GitHub registries it should be fine.

**Comment by beeme1mr** [comment]
Hey @benjiro, would you still like me to investigate MyGet or can this issue be resolved?

**Comment by benjiro** [comment]
@beeme1mr i haven't got around to setting up github publishing but I think it will work for what we want so ill close out this ticket and created https://github.com/open-feature/dotnet-sdk/issues/54
